name: Copy files to test-deploy-serv
on: [push]
jobs:
  Copy-files-to-web-server:
    runs-on: ubuntu-latest
    steps:
      - name: Copy files
        run:
          echo "Clone repo"
          cd /tmp;
          git clone --branch NitroMixer-kh-patch-1 https://github.com/NitroMixer-kh/ci-cd-4-calendar.git;
      - name:
        run:
          cd ci-cd-4-calendar;
          echo "Copying files"
          cp -R * /var/www/calendar;
          echo "Build end";
