name: Copy files to test-deploy-serv
on: [push]
jobs:
  Copy-files-to-web-server:
    runs-on: ubuntu-latest
    steps:
      - name: Copy files
        run:
         cd /tmp;
         git clone https://github.com/NitroMixer-kh/ci-cd-4-calendar.git;
         cd ci-cd-4-calendar;
         rsync -a * /var/www/calendar/
