name: Copy files to web-server
on: [push]
jobs:
  Copy-files-to-web-server:
    runs-on: ubuntu-latest
    steps:
      - name: Copy folder content recursively to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: *.*
          remote: /var/www/calendar
          host: 192.168.122.196
          username: nitromixer
          password: 123321
